baseurl: 'https://kevinmarquesp.github.io/blog'
languageCode: 'pt-br'
title: "Kevin Marques's blog"

theme: 'hugo-theme-stack'
paginate: 10

disqusShortname: 'kevin-marques-blog'


menu:
  main:
    - name: 'Home'
      url: '/'
      identifier: 'home'
      params:
        icon: 'home'
    # note: the 'Archives' and 'Search' options is already there because it has
    # the pages created

  social:
    - identifier: 'github'
      name: 'GitHub'
      url: 'https://github.com/kevinmarquesp'
      params:
        icon: 'brand-github'

    - identifier: 'linkedin'
      name: 'Linkedin'
      url: 'https://www.linkedin.com/in/kevin-marques-827299238/'
      params:
        icon: 'brand-linkedin'


markup:
  tableOfContents:
    endLevel: 6

  goldmark:
    renderer:
      unsafe: true

  highlight:
    lineNos: true


params:
  favicon: 'favicon.svg'

  colorscheme:
    default: 'dark'

  article:
    math: true
    toc: true
    readingTime: true

  sidebar:
    emoji: '🚀'
    subtitle: 'Um desenvolvedor web júnior que é apaixonado por tecnologia e
              aprender coisas novas, bem vindo ao meu diário de bordo!'

  footer:
    since: 2023
    customText: 'Obrigado por ter parado pra visitar meu blog, espero que aproveite
                bem os meus artigos! Talvez você queira dar uma olhada no <a href=
                "https://github.com/kevinmarquesp/blog" target="_blank"><strong>source
                code</strong></a> desse projeto<br>'

  widgets:
    page:
      - type: 'toc'

    homepage:
      - type: 'search'
      - type: 'archives'
        params:
          limit: 6
      - type: 'tag-cloud'
        params:
          limit: 0

  comments:
    enabled: true
    provider: 'disqus'

    disqusjs:
      shortname: "Kevin Marques's blog"
