baseurl: 'https://kevinmarquesp.github.io'
languageCode: 'pt-br'
title: "Kevin Marques"

disqusShortname: 'kevinmarquesp-github-io-blog'
theme: 'hugo-theme-stack'
paginate: 10


menu:
  main:
    - name: 'Blog'
      url: '/'
      identifier: 'blog'
      params:
        icon: 'home'
    # note: the 'Archives' and 'Search' options is already there because it has
    # the pages created

  social:
    - identifier: 'rss'
      name: '[0] RSS Feed'
      url: 'https://kevinmarquesp.github.io/index.xml'
      params:
        icon: 'rss'

    - identifier: 'github'
      name: '[1] GitHub'
      url: 'https://github.com/kevinmarquesp'
      params:
        icon: 'brand-github'

    - identifier: 'linkedin'
      name: '[2] Linkedin'
      url: 'https://www.linkedin.com/in/kevin-marques-827299238/'
      params:
        icon: 'brand-linkedin'


markup:
  tableOfContents:
    endLevel: 6

  goldmark:
    renderer:
      unsafe: true


params:
  favicon: 'favicon.svg'
  rssFullContent: true

  colorscheme:
    default: 'dark'

  article:
    math: true
    toc: true
    readingTime: true

  sidebar:
    emoji: '🚀'
    subtitle: 'Olá, sou um desenvolvedor web júnior apaixonado por tecnologia e
              por aprender coisas novas. Seja bem vindo ao meu diário de bordo!'

  footer:
    since: 2023
    customText: 'Obrigado por ter parado pra visitar meu blog, espero que aproveite
                bem os meus artigos! Talvez você queira dar uma olhada no <a href=
                "https://github.com/kevinmarquesp/blog" target="_blank"><strong>source
                code</strong></a> desse projeto<br>'

  widgets:
    page:
      - type: 'toc'

    homepage:
      - type: 'search'
      - type: 'archives'
        params:
          limit: 6
      - type: 'tag-cloud'
        params:
          limit: 0

  comments:
    enabled: true
    provider: 'disqus'
