baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kevin Marques'
copyright = 'Kevin Marques (CC BY 4.0) | Made with ❤️ from scratch 💪'

[markup.highlight]
lineNos = true
style = 'nord'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
params = { icon = 'bi-house-fill' }

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 20
params = { icon = 'bi-bookmarks-fill' }

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 30
params = { icon = 'bi-pen-fill' }

[[menus.meta]]
name = ''
url = 'https://github.com/kevinmarquesp/kevinmarquesp.github.io'
weight = 10
params = { icon = 'bi-github' }

[[menus.meta]]
name = ' '
url = '/index.xml'
weight = 20
params = { icon = 'bi-rss-fill' }

[services.disqus]
shortname = 'kevinmarquesp-github-io-blog'
